### ISSUE TITLE
Translate SteelColumn/momen Workbench

### ISSUE THREAD

**Issue by luzpaz** [ebrahimraeyat/momen#2]
https://wiki.freecadweb.org/Translating_an_external_workbench  
https://github.com/FreeCAD/Addons/issues/15

**Comment by ebrahimraeyat** [comment]
Hi @luzpaz. I started to prepare the files. but some question:

1. lupdate command don't act recursively, even if I add recursive option.
2. in this step: Send the .ts file to a translation platform, how can I automatically sync that with GitHub?

thanks.

**Comment by luzpaz** [comment]
1. What do you mean? Can you show an example? Also what version of Qt are you running?  
2. We use crowdin scripts to automatically interact with crowdin and github   
See https://wiki.freecadweb.org/Crowdin_Scripts  
We should create a template for external workbench devs

**Comment by luzpaz** [comment]
bump @ebrahimraeyat 

//cc @hasecilu @kaktusus

**Comment by hasecilu** [comment]
Hi, currently I got some errors at startup, maybe with an older AppImage I'm able to test it, I could start checking it like in 3 days

```python
12:43:25  Init:      Initializing /home/uli/.local/share/FreeCAD/Mod/SteelColumn... failed
12:43:25  ----------------------------------------------------------------------------------------------------
12:43:25  Traceback (most recent call last):
  File "<string>", line 142, in RunInitGuiPy
  File "/home/uli/.local/share/FreeCAD/Mod/SteelColumn/InitGui.py", line 28, in <module>
    Gui.addWorkbench(SteelColumnWorkbench())
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uli/.local/share/FreeCAD/Mod/SteelColumn/InitGui.py", line 8, in __init__
    import section
  File "/home/uli/.local/share/FreeCAD/Mod/SteelColumn/section.py", line 12, in <module>
    from PySide2.QtGui import *
  File "/usr/lib/python3.12/site-packages/PySide2/__init__.py", line 107, in <module>
    _setupQtDirectories()
  File "/usr/lib/python3.12/site-packages/PySide2/__init__.py", line 58, in _setupQtDirectories
    import shiboken2
  File "/usr/lib/python3.12/site-packages/shiboken2/__init__.py", line 30, in <module>
    _init_pyside_extension()
    ^^^^^^^^^^^^^^^^^^^^^^
NameError: name '_init_pyside_extension' is not defined
12:43:25  ----------------------------------------------------------------------------------------------------
12:43:25  During initialization the error "name '_init_pyside_extension' is not defined" occurred in /home/uli/.local/share/FreeCAD/Mod/SteelColumn/InitGui.py
12:43:25  Please look into the log file for further information
```

**Comment by luzpaz** [comment]
@ebrahimraeyat :point_up_2:

**Comment by luzpaz** [comment]
bump

**Comment by hasecilu** [comment]
Tested some days ago and replacing `PySide2` with `PySide` works but does that change breaks old versions of FreeCAD? I hope people is on 1.0 now.

**Comment by ebrahimraeyat** [comment]
> Tested some days ago and replacing `PySide2` with `PySide` works but does that change breaks old versions of FreeCAD? I hope people is on 1.0 now.

It did not work with earlier version of FreeCAD, I have v 0.19 and in starts it gives me error:

```bash
No module named 'PySide.QtWidgets'
"C:\Users\ebrahim\AppData\Roaming\FreeCAD\Mod\SteelColumn\column_type.py", line 7, in <module>
    from PySide.QtWidgets import *
```
